### ISSUE TITLE
buy_limit / sell_limit doesn't have OrderType

### ISSUE THREAD

**Issue by kwrooijen** [straw-hat-team/bittrex#24]
Hi, I think I may have come across an issue regarding the buy_limit and sell_limit API calls (possibly more?).

When formatting the return value of these calls, Order.new is used. However in Order.new the function `get_order_type` is called.
https://github.com/straw-hat-team/bittrex/blob/e296e3f6602926d9eddd303ac474343838199634/lib/bittrex/order.ex#L71-L74
The problem is that these 2 API calls only return a uuid, and do not contain this field. Thus this function will return `nil` and crash at `String.upcase`
https://github.com/straw-hat-team/bittrex/blob/e296e3f6602926d9eddd303ac474343838199634/lib/bittrex/order.ex#L32

I think the best solution is to modify the `result` variable and include this field manually, which shouldn't be to difficult.

https://github.com/straw-hat-team/bittrex/blob/e296e3f6602926d9eddd303ac474343838199634/lib/bittrex/interactor/market/sell_limit.ex#L20-L22

I could open a PR but I first wanted to hear your opinion on this.

Thanks!

**Comment by kwrooijen** [comment]
Update: Another issue I've just come across is that it doesn't cover OrderStatus either.
https://github.com/straw-hat-team/bittrex/blob/e296e3f6602926d9eddd303ac474343838199634/lib/bittrex/order/order_status.ex#L7-L19

Neither of these cases match these API calls.

**Comment by yordis** [comment]
@kwrooijen open a new issue for the `OrderStatus` one so we separate the issues?
